{% set name = 'jupyter_nbextensions_configurator' %}
{% set version = '0.2.1' %}
{% set md5 = '86efebd441f4404a6194d11c14383430' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    md5: {{ md5 }}

build:
  number: 2
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - jupyter_contrib_core >=0.2
    - jupyter_core
    - nbconvert
    - notebook >=4.0
    - pyyaml
    - setuptools
    - tornado
    - traitlets

test:
  imports:
    - jupyter_nbextensions_configurator
    - jupyter_nbextensions_configurator.application

  commands:
    - jupyter nbextensions_configurator --help
    - jupyter nbextensions_configurator enable --help
    - jupyter nbextensions_configurator disable --help

about:
  summary: A server extension for jupyter notebook providing configuration interfaces for notebook extensions (nbextensions).
  home: https://github.com/jupyter-contrib/jupyter_nbextensions_configurator
  license_file: LICENSE.txt
  license: BSD 3-clause

extra:
  recipe-maintainers:
    - jcb91
