{% set version = "4.1.0" %}

package:
  name: nbformat
  version: {{ version }}

source:
  fn: nbformat-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/n/nbformat/nbformat-{{ version }}.tar.gz
  sha256: dbf6c0ed0cb7c5a7184536368f1dd1ada2d48fd6f016e0f9e9b69236e28c0857

build:
  number: 0
  script: pip install --no-deps .
  # fixme: remove redundant conda entrypoints when we can
  entry_points:
    - jupyter-trust = nbformat.sign:TrustNotebookApp.launch_instance

requirements:
  build:
    - python
    - pip
  run:
    - python
    - ipython_genutils
    - traitlets
    - jsonschema >=2.0,!=2.5.0
    - jupyter_core

test:
  commands:
    - jupyter-trust -h
  imports:
    - nbformat

about:
  home: http://jupyter.org
  license: BSD 3-clause
  summary: the base implementation of the Jupyter Notebook format

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - takluyver
    - ocefpaf
