{% set version = "1.11.1" %}

{% set variant = "openblas" %}

package:
  name: numpy
  version: {{ version }}

source:
  fn: numpy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/n/numpy/numpy-{{ version }}.tar.gz
  md5: 2f44a895a8104ffac140c3a70edbd450

build:
  number: 201
  # We lack openblas on Windows, and therefore can't build numpy there either currently.
  skip: true  # [win]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - cython
    - python
    - setuptools
    - blas 1.1 {{ variant }}
    - openblas 0.2.18*
  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas 0.2.18*

test:
  requires:
    - nose
  commands:
    - f2py -h
  imports:
    - numpy
    - numpy.linalg.lapack_lite

about:
  home: http://numpy.scipy.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: array processing for numbers, strings, records, and objects.

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
    - rgommers
    - ocefpaf
