# This file created by conda-build 1.20.3
# meta.yaml template originally from:
# /recipe_root, last modified Wed Jun  8 15:12:49 2016
# ------------------------------------------------

package:
    name: sqlite
    version: 3.13.0
source:
    fn: sqlite-autoconf-3130000.tar.gz
    patches: ''
    sha256: e2797026b3310c9d08bd472f6d430058c6dd139ff9d4e30289884ccd9744086b
    url: https://www.sqlite.org/2016/sqlite-autoconf-3130000.tar.gz
build:
    features: ''
    number: '1'
requirements:
    build: ''
test:
    commands:
        - sqlite3 --version
    requires: ''
about:
    home: http://www.sqlite.org/
    license: Public-Domain (http://www.sqlite.org/copyright.html)
    license_family: Public-Domain
    summary: implements a self-contained, zero-configuration, SQL database engine
extra:
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - msarahan
