# This file created by conda-build 1.20.3
# meta.yaml template originally from:
# /recipe_root, last modified Tue Jun  7 01:59:52 2016
# ------------------------------------------------

package:
    name: sip
    version: '4.18'
source:
    fn: sip-4.18.tar.gz
    sha1: 6704854bc684de3b76c9db61ce54a74e7de5cf45
    url: http://sourceforge.net/projects/pyqt/files/sip/sip-4.18/sip-4.18.tar.gz
build:
    number: '0'
requirements:
    build:
        - python
    run:
        - python
test:
    files:
        - test
    imports:
        - sip
about:
    home: http://www.riverbankcomputing.com/software/sip/intro
    license: GPL3
    summary: Create Python bindings for C and C++ libraries
extra:
    recipe-maintainers:
        - ccordoba12
        - msarahan
