{% set version = "4.0.10" %}

package:
  name: decorator
  version: {{ version }}

source:
  fn: decorator-{{ version }}.tar.gz
  url: https://github.com/micheles/decorator/archive/{{ version }}.tar.gz
  sha256: 89d9874d29f422ad97a2769646a1a9256bb365a79ddfbbda71a62f33e774100d

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - decorator

about:
  home: https://github.com/micheles/decorator
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Better living through Python with decorators

extra:
  recipe-maintainers:
    - msarahan
    - pelson
    - ocefpaf
