# This file created by conda-build 1.20.3
# meta.yaml template originally from:
# /recipe_root, last modified Thu May 19 17:32:05 2016
# ------------------------------------------------

package:
    name: readline
    version: '6.2'
source:
    fn: readline-6.2.tar.gz
    md5: 67948acb2ca081f23359d0256e9a271c
    patches:
        - patches/readline62-001
        - patches/readline62-002
        - patches/readline62-003
        - patches/readline62-004
        - patches/readline62-005
    url: ftp://ftp.gnu.org/gnu/readline/readline-6.2.tar.gz
build:
    number: '0'
requirements:
    build:
        - pkg-config
        - ncurses 5.9*
    run:
        - ncurses 5.9*
test:
    commands:
        - test -f ${PREFIX}/lib/libreadline.a
        - test -f ${PREFIX}/lib/libreadline.so
        - test -f ${PREFIX}/lib/libhistory.a
        - test -f ${PREFIX}/lib/libhistory.so
about:
    home: https://cnswww.cns.cwru.edu/php/chet/readline/rltop.html
    license: GPL3
    summary: library for editing command lines as they are typed in
extra:
    recipe-maintainers:
        - croth1
        - jakirkham
        - jjhelmus
        - pelson
        - msarahan
